CREATE TABLE CADASTRO_IMOVEL (
    ID_CADASTRO_IMOVEL INT PRIMARY KEY AUTO_INCREMENT,
    TITULO_IMOVEL VARCHAR(255),
    ENDERECO VARCHAR(255),
    NUM_QUARTOS VARCHAR(33),
    NUM_BANHEIROS VARCHAR(33),
    NUM_VAGAS VARCHAR(33),
    VALOR_NOITE VARCHAR(33),
    IMAGENS VARCHAR(255),
    OBS VARCHAR(255),
    EMAIL VARCHAR(255),
    TELEFONE VARCHAR(19),
    ID_USER INT,
    FOREIGN KEY (ID_USER) REFERENCES CADASTRO(ID)
);
