CREATE TABLE CADASTRO (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOME_COMPLETO VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) UNIQUE NOT NULL,
    CPF CHAR(11) NOT NULL,
    TELEFONE VARCHAR(19),
    SENHA VARCHAR(255) NOT NULL,
    REPETE_SENHA VARCHAR(255) NOT NULL
);